name: gym-hs
version: 0.1.0.1
synopsis: Haskell bindings for OpenAI Gymnasium
description: |
  A Haskell library that provides bindings to OpenAI Gymnasium environments.
  This library enables you to call any Gymnasium environment from Haskell code
  with a simple, type-safe API. It uses subprocess-based communication to
  interface with Python's Gymnasium library, providing full access to the
  rich ecosystem of reinforcement learning environments.
  .
  A full example using Gymnasium to implement a DQN solving CartPole is here: https://github.com/Xodarap/hs-gym-example
homepage: https://github.com/Xodarap/haskell-gymnasium
bug-reports: https://github.com/Xodarap/haskell-gymnasium/issues
license: MIT
license-file: LICENSE
author: Ben West
maintainer: xodarap00@gmail.com
copyright: 2025 Ben West
category: AI, Machine Learning, Reinforcement Learning
build-type: Custom
custom-setup:
  dependencies:
  - base
  - Cabal
  - process
extra-source-files:
- README.md
- CHANGELOG.md
tested-with: GHC==9.6.7

source-repository:
  type: git
  location: https://github.com/Xodarap/haskell-gymnasium

dependencies:
- base >= 4.7 && < 5
- process >= 1.6 && < 1.7
- aeson >= 2.0 && < 2.3
- bytestring >= 0.10 && < 0.13
- text >= 1.2 && < 2.2
- scientific >= 0.3 && < 0.4
- containers >= 0.6 && < 0.8
- unordered-containers >= 0.2 && < 0.3
- vector >= 0.12 && < 0.14

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Gym.Core
  - Gym.Environment
  other-modules:
  - Gym.Internal.Python

executables:
  gym-hs-example:
    main: Main.hs
    source-dirs: app
    dependencies:
    - gym-hs

tests:
  gym-hs-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - gym-hs
    - hspec >= 2.7
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N