name: gym-hs
version: 0.1.0.0
synopsis: Haskell bindings for OpenAI Gymnasium
description: A Haskell library that provides bindings to OpenAI Gymnasium environments
license: MIT
author: gym-hs contributors
maintainer: gym-hs@example.com
category: AI

dependencies:
- base >= 4.7 && < 5
- process >= 1.6
- aeson >= 2.0
- bytestring >= 0.10
- text >= 1.2
- vector >= 0.12
- containers >= 0.6
- unordered-containers >= 0.2
- scientific >= 0.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Gym.Core
  - Gym.Environment
  other-modules:
  - Gym.Internal.Python

executables:
  gym-hs-example:
    main: Main.hs
    source-dirs: app
    dependencies:
    - gym-hs

tests:
  gym-hs-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - gym-hs
    - hspec >= 2.7
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N